[supabase]
url = "https://kxclelcurmlezfzifnzf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Y2xlbGN1cm1sZXpmemlmbnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MTAyMDUsImV4cCI6MjA4NTI4NjIwNX0.eq0OLppyCmlc06zAKqOMsgvyNiw2i7zoFefDuKIiENQ"
